### ISSUE TITLE
Many issues

### ISSUE THREAD

**Issue by kamalkech** [MarcHanin/drun#5] opened 2020-05-22 23:03 UTC
after installation 

1- commande `drun help` not working
2- how we can add multiple permissions on the command line
for example :
- `drun watch --entryPoint=./index.ts --cwd=./ --runtimeOptions=--allow-net` working
- `drun watch --entryPoint=./index.ts --cwd=./ --runtimeOptions=--allow-net--allow-write --allow-read `all permissions not working
- `drun watch --entryPoint=./index.ts --cwd=./ --runtimeOptions=--allow-net, --allow-write, --allow-read` all permissions not working

**Comment by MarcHanin** [comment] 2020-05-23 00:06
Hi @kamalkech,
Thanks for reporting this issue.
Can I have more informations about your errors and your environment like your OS, your Deno version and your Drun version ?

**Comment by MarcHanin** [comment] 2020-05-29 23:16
Since I have no answer and I can't reproduce your error I will close this issue. Feel free to re-open it if necessary.

**Closed as completed by MarcHanin** 2020-05-29 23:16 UTC
